import { Task } from '@/lib/types';

export const exportToJSON = (tasks: Task[], filename: string = 'kanbi-board') => {
  const dataStr = JSON.stringify(tasks, null, 2);
  const dataBlob = new Blob([dataStr], { type: 'application/json' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}-${new Date().toISOString().split('T')[0]}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportToCSV = (tasks: Task[], filename: string = 'kanbi-board') => {
  const headers = ['Title', 'Description', 'Status', 'Priority', 'Due Date', 'Tags', 'Created At'];
  const rows = tasks.map(task => [
    `"${(task.title || '').replace(/"/g, '""')}"`,
    `"${(task.description || '').replace(/"/g, '""')}"`,
    task.status,
    task.priority,
    task.dueDate || '',
    task.tags?.join('; ') || '',
    task.createdAt || ''
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n');

  const dataBlob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}-${new Date().toISOString().split('T')[0]}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const exportToMarkdown = (tasks: Task[], filename: string = 'kanbi-board') => {
  const todoTasks = tasks.filter(t => t.status === 'To Do');
  const inProgressTasks = tasks.filter(t => t.status === 'In Progress');
  const doneTasks = tasks.filter(t => t.status === 'Done');

  const formatTask = (task: Task) => {
    let md = `### ${task.title}\n\n`;
    if (task.description) md += `${task.description}\n\n`;
    md += `- **Priority:** ${task.priority}\n`;
    if (task.dueDate) md += `- **Due Date:** ${task.dueDate}\n`;
    if (task.tags && task.tags.length > 0) md += `- **Tags:** ${task.tags.join(', ')}\n`;
    md += `- **Created:** ${new Date(task.createdAt || '').toLocaleDateString()}\n\n`;
    return md;
  };

  let markdown = `# Kanbi Board Export\n\n`;
  markdown += `**Exported:** ${new Date().toLocaleString()}\n\n`;
  markdown += `**Total Tasks:** ${tasks.length} | **Completed:** ${doneTasks.length} (${Math.round((doneTasks.length / tasks.length) * 100)}%)\n\n`;
  markdown += `---\n\n`;

  if (todoTasks.length > 0) {
    markdown += `## 📋 To Do (${todoTasks.length})\n\n`;
    todoTasks.forEach(task => markdown += formatTask(task));
  }

  if (inProgressTasks.length > 0) {
    markdown += `## 🚀 In Progress (${inProgressTasks.length})\n\n`;
    inProgressTasks.forEach(task => markdown += formatTask(task));
  }

  if (doneTasks.length > 0) {
    markdown += `## ✅ Done (${doneTasks.length})\n\n`;
    doneTasks.forEach(task => markdown += formatTask(task));
  }

  markdown += `---\n\n*Generated by Kanbi - AI-Powered Task Management*`;

  const dataBlob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${filename}-${new Date().toISOString().split('T')[0]}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
