import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Table, TableRow, TableCell, WidthType, BorderStyle } from 'docx';

interface Task {
  id: string;
  title: string;
  priority: string;
  status: string;
  owner?: string;
  deadline?: string;
}

interface BoardData {
  title: string;
  tasks: Task[];
  createdAt?: string;
  userName?: string;
}

export class DocxExporter {
  static async export(boardData: BoardData): Promise<Buffer> {
    const { title, tasks, createdAt, userName } = boardData;

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: title,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Created: ${createdAt || new Date().toLocaleDateString()}`, size: 20 }),
              new TextRun({ text: ` | By: ${userName || 'User'}`, size: 20 }),
              new TextRun({ text: ` | Total Tasks: ${tasks.length}`, size: 20, bold: true }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),
          ...this.createTasksByStatus(tasks, 'To Do'),
          ...this.createTasksByStatus(tasks, 'In Progress'),
          ...this.createTasksByStatus(tasks, 'Done'),
          new Paragraph({
            text: '---',
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: 'Generated by KANBI - AI Task Management', size: 18, italics: true }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      }],
    });

    return await Packer.toBuffer(doc);
  }

  private static createTasksByStatus(tasks: Task[], status: string): Paragraph[] {
    const filtered = tasks.filter(t => t.status === status);
    if (filtered.length === 0) return [];

    const paragraphs: Paragraph[] = [
      new Paragraph({
        text: status,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }),
    ];

    filtered.forEach((task, index) => {
      const priorityEmoji = this.getPriorityEmoji(task.priority);
      
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${index + 1}. ${priorityEmoji} `, bold: true }),
            new TextRun({ text: task.title, bold: true }),
          ],
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: `   Priority: ${task.priority} | Owner: ${task.owner || 'Me'} | Deadline: ${task.deadline || 'Not set'}`, size: 20 }),
          ],
          spacing: { after: 200 },
        })
      );
    });

    return paragraphs;
  }

  private static getPriorityEmoji(priority: string): string {
    const map: Record<string, string> = {
      'Urgent': '🔴',
      'High': '🟠',
      'Medium': '🟡',
      'Low': '🟢',
    };
    return map[priority] || '⚪';
  }
}
