import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import {
  BOARD_TASK_COLUMNS,
  PRIORITY_LABELS,
  type BoardTaskPriority,
  type BoardTaskStatus,
} from '@/lib/constants';

/** A task as stored on the board. Priority and status are the storage casings. */
export interface ExportedTask {
  id?: string;
  title: string;
  priority: BoardTaskPriority;
  status: BoardTaskStatus;
  label?: string;
  dueDate?: string;
  estimate?: string;
}

interface BoardData {
  title: string;
  tasks: ExportedTask[];
  createdAt?: string;
  userName?: string;
}

export class DocxExporter {
  static async export(boardData: BoardData): Promise<Buffer> {
    const { title, tasks, createdAt, userName } = boardData;

    const doc = new Document({
      sections: [{
        properties: {},
        children: [
          new Paragraph({
            text: title,
            heading: HeadingLevel.HEADING_1,
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: `Created: ${createdAt || new Date().toLocaleDateString()}`, size: 20 }),
              new TextRun({ text: ` | By: ${userName || 'User'}`, size: 20 }),
              new TextRun({ text: ` | Total Tasks: ${tasks.length}`, size: 20, bold: true }),
            ],
            alignment: AlignmentType.CENTER,
            spacing: { after: 600 },
          }),
          // flatMap, not map, so each column's paragraphs are spliced in rather
          // than nested as arrays inside the section.
          ...BOARD_TASK_COLUMNS.flatMap((column) => this.createTasksByStatus(tasks, column)),
          new Paragraph({
            text: '---',
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: 'Generated by KANBI - AI Task Management', size: 18, italics: true }),
            ],
            alignment: AlignmentType.CENTER,
          }),
        ],
      }],
    });

    return await Packer.toBuffer(doc);
  }

  private static createTasksByStatus(
    tasks: ExportedTask[],
    column: (typeof BOARD_TASK_COLUMNS)[number]
  ): Paragraph[] {
    const filtered = tasks.filter((t) => t.status === column.status);
    if (filtered.length === 0) return [];

    const paragraphs: Paragraph[] = [
      new Paragraph({
        text: column.label,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }),
    ];

    filtered.forEach((task, index) => {
      const details = [
        `Priority: ${PRIORITY_LABELS[task.priority]}`,
        task.label ? `Label: ${task.label}` : null,
        task.estimate ? `Estimate: ${task.estimate}` : null,
        `Due: ${task.dueDate || 'Not set'}`,
      ].filter(Boolean).join(' | ');

      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${index + 1}. `, bold: true }),
            new TextRun({ text: task.title, bold: true }),
          ],
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [new TextRun({ text: `   ${details}`, size: 20 })],
          spacing: { after: 200 },
        })
      );
    });

    return paragraphs;
  }
}
