import jsPDF from 'jspdf';

interface Task {
  id: string;
  title: string;
  priority: string;
  status: string;
  owner?: string;
  deadline?: string;
}

interface BoardData {
  title: string;
  tasks: Task[];
  createdAt?: string;
  userName?: string;
}

export class PdfExporter {
  static async export(boardData: BoardData): Promise<Buffer> {
    const { title, tasks, createdAt, userName } = boardData;
    const doc = new jsPDF();

    let yPos = 20;

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 105, yPos, { align: 'center' });
    yPos += 15;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Created: ${createdAt || new Date().toLocaleDateString()} | By: ${userName || 'User'} | Total: ${tasks.length} tasks`, 105, yPos, { align: 'center' });
    yPos += 15;

    const statuses = ['To Do', 'In Progress', 'Done'];
    
    for (const status of statuses) {
      const filtered = tasks.filter(t => t.status === status);
      if (filtered.length === 0) continue;

      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(status, 20, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');

      filtered.forEach((task, index) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        const priorityColor = this.getPriorityColor(task.priority);
        doc.setFillColor(priorityColor.r, priorityColor.g, priorityColor.b);
        doc.circle(22, yPos - 2, 2, 'F');

        const taskText = `${index + 1}. ${task.title}`;
        const lines = doc.splitTextToSize(taskText, 160);
        doc.text(lines, 27, yPos);
        yPos += lines.length * 5;

        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text(`Priority: ${task.priority} | Owner: ${task.owner || 'Me'} | Deadline: ${task.deadline || 'Not set'}`, 27, yPos);
        doc.setTextColor(0);
        doc.setFontSize(10);
        yPos += 8;
      });

      yPos += 5;
    }

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by KANBI - AI Task Management', 105, 285, { align: 'center' });

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    return pdfBuffer;
  }

  private static getPriorityColor(priority: string): { r: number; g: number; b: number } {
    const colors: Record<string, { r: number; g: number; b: number }> = {
      'Urgent': { r: 239, g: 68, b: 68 },
      'High': { r: 249, g: 115, b: 22 },
      'Medium': { r: 234, g: 179, b: 8 },
      'Low': { r: 34, g: 197, b: 94 },
    };
    return colors[priority] || { r: 156, g: 163, b: 175 };
  }
}
