import jsPDF from 'jspdf';
import {
  BOARD_TASK_COLUMNS,
  PRIORITY_LABELS,
  type BoardTaskPriority,
  type BoardTaskStatus,
} from '@/lib/constants';
import type { ExportedTask } from './docx-exporter';

interface BoardData {
  title: string;
  tasks: ExportedTask[];
  createdAt?: string;
  userName?: string;
}

export class PdfExporter {
  static async export(boardData: BoardData): Promise<Buffer> {
    const { title, tasks, createdAt, userName } = boardData;
    const doc = new jsPDF();

    let yPos = 20;

    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 105, yPos, { align: 'center' });
    yPos += 15;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Created: ${createdAt || new Date().toLocaleDateString()} | By: ${userName || 'User'} | Total: ${tasks.length} tasks`, 105, yPos, { align: 'center' });
    yPos += 15;

    for (const column of BOARD_TASK_COLUMNS) {
      const filtered = tasks.filter((t) => t.status === column.status);
      if (filtered.length === 0) continue;

      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text(column.label, 20, yPos);
      yPos += 8;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');

      filtered.forEach((task, index) => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        const priorityColor = this.getPriorityColor(task.priority);
        doc.setFillColor(priorityColor.r, priorityColor.g, priorityColor.b);
        doc.circle(22, yPos - 2, 2, 'F');

        const taskText = `${index + 1}. ${task.title}`;
        const lines = doc.splitTextToSize(taskText, 160);
        doc.text(lines, 27, yPos);
        yPos += lines.length * 5;

        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text(detailsLine(task), 27, yPos);
        doc.setTextColor(0);
        doc.setFontSize(10);
        yPos += 8;
      });

      yPos += 5;
    }

    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text('Generated by KANBI - AI Task Management', 105, 285, { align: 'center' });

    const pdfBuffer = Buffer.from(doc.output('arraybuffer'));
    return pdfBuffer;
  }

  private static getPriorityColor(priority: BoardTaskPriority): { r: number; g: number; b: number } {
    return PRIORITY_RGB[priority] ?? { r: 156, g: 163, b: 175 };
  }
}

const PRIORITY_RGB: Record<BoardTaskPriority, { r: number; g: number; b: number }> = {
  urgent: { r: 225, g: 29, b: 72 },
  high: { r: 234, g: 88, b: 12 },
  medium: { r: 202, g: 138, b: 4 },
  low: { r: 22, g: 163, b: 74 },
};

/** Detail line under each task, using the same fields as the DOCX export. */
function detailsLine(task: ExportedTask): string {
  return [
    `Priority: ${PRIORITY_LABELS[task.priority] ?? task.priority}`,
    task.label ? `Label: ${task.label}` : null,
    task.estimate ? `Estimate: ${task.estimate}` : null,
    `Due: ${task.dueDate || 'Not set'}`,
  ]
    .filter(Boolean)
    .join(' | ');
}
